l_german:
 DIVISION_QUEUED:0 "$N$ Division"
 DIVISIONS_QUEUED:0 "$N$ Divisionen"
 CONVEYOR_EQUIPMENT_NEED:0 "Ausrüstung benötigt:"
 CONVEYOR_MANPOWER_NEED:0 "Benötigte Mannstärke: $AMOUNT|H$"
 DEPLOYMENT_REQUIREMENT:0 "$NAME$: $AMOUNT$"
 DEPLOYMENT_DIVISION_LABEL:0 "Division"
 DEPLOYMENT_PROGRESS_LABEL:0 "Fortschritt"
 DEPLOYMENT_PRIORITY_LABEL:0 "Priorität"
 DEPLOYMENT_DEPLOY_LABEL:0 "Einsetzen"
 DEPLOYMENT_TEMPLATE_ITEM_ADD:0 "§GKlicken, um Ausbildung zu starten§!"
 DEPLOYMENT_TEMPLATE_ITEM_EDIT:0 "§GKlicken, um Divisionsvorlage zu bearbeiten§!"
 DEPLOYMENT_TRAINING:0 "Ausbildung: $VALUE|%Y0$ $MAXVALUE|$"
 DEPLOYMENT_TRAINING_MAXVALUE_DESC:0 "/ $VALUE|H%0$ (Maximum hängt von der vorhandenen Ausrüstungsmenge ab)"
 DEPLOYMENT_CURRENT_LEVEL:0 "Aktuelle Erfahrungsstufe: $NUMBER$ ( $LEVEL|%Y0$ )"
 DEPLOYMENT_MANPOWER_DESC:0 "Mannstärke: $VALUE|Y0$ ( $MAX|Y0$ Max.)"
 DEPLOYMENT_EXPERIENCE_DESC:0 "\nNach Abschluss der Ausbildung startet diese Einheit auf Erfahrungsstufe $NUMBER$ ( $MAXLEVEL|%Y0$ ). Dies reduziert ihren Kampfmalus auf $EFFECT|+=%0$."
 DEPLOYMENT_EXPERIENCE_ESTIMATED_DESC:0 "\nEnde der Ausbildung bei optimaler Versorgung: §Y$DATE$§!."
 DEPLOYMENT_EQUIPMENT:0 "Ausrüstung: $VALUE|%Y0$"
 DEPLOYMENT_EQUIPMENT_FULL_DESC:0 "$NAME$: $VALUE|G0$/$MAX|G0$"
 DEPLOYMENT_EQUIPMENT_DESC:0 "$NAME$: $VALUE|Y0$/$MAX|Y0$"
 DEPLOYMENT_DESIGNER:0 "Divisions-Designer"
 DEPLOYMENT_EQUIPMENT_VARIANT_AMOUNT:0 "        $NAME|Y$: $VALUE|Y0$"
 DEPLOYMENT_EQUIPMENT_VARIANT_AMOUNT_FULL:0 "        $NAME|G$: $VALUE|G0$"
 DEPLOYMENT_EQUIPMENT_CHANGE:0 "$NAME$: $VALUE$"
 DEPLOYMENT_ADD_TEMPLATE:0 "Ausbilden"
 DEPLOYMENT_LINES_HIT_THE_CAP:0 "Wir können maximal $CAP|*H$ Männer ausbilden.\nDie Obergrenze wird durch die max. Mannstärke im Feld vorgegeben ( $RATIO|H0%$ von $INFIELD|*H$. Minimum: $MINPOSSIBLE|*H$ Männer)"
 REGIMENTS_SELECTION_CANCEL:0 "Zurück"
 ONLY_ONE_TEMPLATE_LEFT:0 "Sie können Ihre letzte Vorlage nicht löschen."
 DELETE_TEMPLATE:0 "Vorlage aus der Liste §Rlöschen§!."
 DELETE_TEMPLATE_TITLE:0 "Vorlage löschen"
 DELETE_TEMPLATE_DESC:0 "Wollen Sie diese Vorlage wirklich löschen?"
 DEPLOYMENT_REMOVE_DIVISION:0 "Division abbrechen"
 DEPLOYMENT_DEPLOYMENT_LABEL:0 "Rekrutierung"
 DEPLOYMENT_NOT_ALLOWED_REASON_EQUIPMENT:0 "Kann keine Einheit §Reinsetzen§!, die nicht ausgerüstet ist. Bitte warten, bis sie mit Ausrüstung versorgt wurde.\n"
 DEPLOYMENT_NOT_ALLOWED_REASON_MANPOWER:0 "Kann keine Einheit §Reinsetzen§!, die keine Männer hat."
 DEPLOYMENT_HOW_TO_DESC:0 "Einsätze aus der Liste auswählen und anschließend auf die markierten Provinzen auf der Karte §Gklicken§!, um sie zu einzusetzen.\n§gEinheiten, die mit unvollständiger Ausrüstung eingesetzt werden, erhalten diese durch Anfragen auf Verstärkung.\nBeachten Sie, dass Einheiten, die zu früh eingesetzt werden, keine ordnungsgemäße Ausbildung erhalten.§!"
REINFORCEMENT:0 "Verstärkungen"
 REINFORCEMENT_DESC:0 "§TPriorität für die Ausrüstung einstellen, mit der die aktiven Truppen verstärken werden, im Vergleich zur Einsatzliste und den Verbesserungen§!"
 REINFORCEMENT_EMPTY:0 "§GAktuell keine Ausrüstungsanfragen.§!"
 UPGRADES:0 "Verbesserungen"
 group_infantry_title:0 "Infanteriebataillone"
 group_mobile_title:0 "Mobile Bataillone"
 group_armor_title:0 "Gepanzerte Bataillone"
 group_artillery_title:0 "Hauptunterstützungsbattalione"
 group_support_title:0 "Unterstützungsbattalions"
 group_schutzstaffel_title:0 "SS Inf.battalione"
 group_schutzstaffel_mobile_title:0 "SS Mobile Battalione"
 group_schutzstaffel_artillery_title:0 "SS Hauptunterstützungsbattalione"
 group_schutzstaffel_panzer_title:0 "SS Panzerbattalione"
 NEW_GROUP_ADDITIONAL_COST:0 "Neue Gruppe $VALUE|H0$£army_experience£"
 UPGRADES_DESC:0 "§TPriorität für die Ausrüstung einstellen, mit der die aktiven Truppen verstärken werden, im Vergleich zur Einsatzliste und den Verbesserungen§!"
 UPGRADES_EMPTY:0 "§GAktuell keine Aufrüstungsanfragen.§!"
 TIMED_ACTIVITY_TITLE:0 "$NAME$ gegen $COUNTRY$"
 TIMED_ACTIVITY_ALERT_TITLE:0 "$NAME|H$ gegen $COUNTRY|H$"
 TIMED_ACTIVITY_ENTRY_DESC:0 "§TPriorität für die Ausrüstung einstellen, mit der diese diplomatische Aktivität unterstützt wird.§!"
  TIMED_ACTIVITY_ENTRY_COMPLETE_DESC:0 "§GMaximale Ausrüstung gesammelt.§!"
 LAND_DEPLOYMENT:0 "§TAuftrag für Landeinheit§!"
 AIR_DEPLOYMENT:0 "§TAuftrag für Flugzeug§!"
 NAVAL_DEPLOYMENT:0 "§TAuftrag für Schiff§!"
 DIVISION_DESIGNER_RENAME:0 "Umbenennen"
 DIVISION_DESIGNER_UPDATE:0 "Aktualisieren"
 DEPLOY:0 "Einsetzen"
 EDIT:0 "Bearbeiten"
 VIEW:0 "Ansehen"
 COPY:0 "Kopieren"
 DIVISION_EQUIPMENT:0 "Divisionsausrüstung"
 NEW_EQUIPMENT_ALLOWED:0 "Neue Ausrüstung benutzen"
 DO_NOT_CONTAINS_TEMPLATE:0 "§RDiese Vorlage kann nicht gelöscht werden. Das Land umfasst nicht diese Vorlage.§!"
 HAS_ARMIES_WITH_TEMPLATE:0 "§RDiese Vorlage kann nicht gelöscht werden, da sie von $AMOUNT|H$ Division(en) verwendet wird.§!"
 HAS_ARMIES_WITH_OLD_TEMPLATE:0 "§RDiese Vorlage kann nicht gelöscht werden, weil $AMOUNT|H$ Division(en) dabei sind, von dieser Vorlage auf eine andere zu wechseln (d.h. sie warten auf Ausrüstung, die zur neuen Vorlage passt).§!"
 HAS_DEPLOYMENT_CONVEYORS_WITH_TEMPLATE:0 "Diese Vorlage kann nicht aus dem Land §Rentfernt§! werden. Land hat $AMOUNT|H$ Einsätze, die diese Vorlage verwenden."
 DEPLOYMENT_TEMPLATE_LABEL:0 "Vorlagen"
 TEMPLATE_PRIO_0:0 "Reserven"
 TEMPLATE_PRIO_0_DESC:0 "Einheiten mit dieser Einstellung erhalten Ausrüstung und Verstärkung mit niedrigster Priorität. Perfekt für Garnisonen und dergleichen."
 TEMPLATE_PRIO_1:0 "Standard"
 TEMPLATE_PRIO_1_DESC:0 "Einheiten mit dieser Einstellung erhalten Ausrüstung und Verstärkung mit normaler Priorität."
 TEMPLATE_PRIO_2:0 "Elite"
 TEMPLATE_PRIO_2_DESC:0 "Einheiten mit dieser Einstellung erhalten Ausrüstung und Verstärkung mit höchster Priorität. Verwenden Sie diese Einstellung für Ihre besten Truppen, die am meisten bewirken können."
 DEPLOYMENT_LEND_LEASE_COUNTRY:0 "Leih-Pacht-Abkommen: $COUNTRY$"
 ADD_CONVEYOR_LINE_BUTTON_LABEL:0 "Hinzufügen"
 ADD_CONVEYOR_LINE_BUTTON_DESC:0 "Fügt eine weitere Einheit $CONVEYOR|H$ zur parallelen Produktion hinzu.\n\n§GUmschalt+Maustaste§!, um 5 Einheiten hinzuzufügen"
 CONVEYOR_GENERIC_NAME_EDIT_DESC:0 "Hier klicken, um die Bezeichnung der Einheiten zu ändern."
 CONVEYOR_TEMPLATE_ICON_DESC:0 "Dieser Auftrag erstellt Divisionen, die die Vorlage $TEMPLATE|H$ verwenden."
 CANCEL_CONVEYOR_TOOLTIP:0 "Produktion aller Einheiten §Rabbrechen§!."
 DEPLOY_CONVEYOR_TOOLTIP:0 "§GKlicken§!, um alle Einheiten sofort einzusetzen."
 DEPLOY_CONVEYOR_DISABLED_TOOLTIP:0 "Es ist keine Einheit §Reinsatzbereit§!"
 CONVEYOR_CANCEL_TITLE:0 "§RAbbrechen§! Produktion"
 CONVEYOR_CANCEL_DESC:0 "Wollen Sie die Produktion aller Einheiten wirklich §Rabbrechen§!?"
 CONVEYOR_LINE_CANCEL_DESC:0 "Produktion dieser Einheit §Rabbrechen§!."
 CONVEYOR_LINE_CANCEL_ACCEPT_TITLE:0 "Auftrag §Rabbrechen§!"
 CONVEYOR_LINE_CANCEL_ACCEPT_SINGLE_DESC:0 "Wollen Sie die Produktion dieses Auftrags wirklich §Rabbrechen§!?\n(Einheit wird ebenfalls §Rentfernt§! )"
 CONVEYOR_LINE_CANCEL_ACCEPT_DESC:0 "Wollen Sie die Produktion dieser Auftrags wirklich §Rabbrechen§!?"
 CONVEYOR_GROUP_ASSIGN_DESC:0 "§GKlicken§!, um Einheit dem Befehl zuzuweisen.\n§GRechtsklicken§!, um Befehlszuweisung zurückzusetzen."
 CONVEYOR_GROUP_CAN_NOT_ASSIGN_NO_ORDERS_DESC:0 "Einheit sollte mindestens einen Befehl am Schauplatz haben, um einer beliebigen Gruppe zugewiesen zu werden."
 CONVEYOR_GROUP_CAN_NOT_ASSIGN_NO_LOCATION_DESC:0 "Einheit sollte ein Zielgebiet haben, um einer beliebigen Gruppe zugewiesen zu werden."
 CONVEYOR_SET_LOCATION_DESC:0 "§GKlicken§!, um Einsatzgebiet für diese Einheit festzulegen.\n§GRechtsklicken§!, um Gebiet zurückzusetzen."
 CONVEYOR_SET_LOCATION_NOT_SET:0 "§RKein Gebiet festgelegt§!"
 CONVEYOR_LINE_PREFIX_NAME_EDIT_DESC:0 "Hier klicken, um Präfix der Einheit zu ändern."
 CONVEYOR_LINE_DEPLOY_DESC:0 "§GKlicken§!, um diese Einheit sofort einzusetzen."
 CONVEYOR_SERIES_INCREASE_DESC:0 "Erhöht die Anzahl der Divisionen, die pro Auftrag erstellt wird.\n\nMit der Einstellung 'endlos' bildet jeder Auftrag eine neue Division aus, sobald die vorherige Division eingesetzt wurde."
 CONVEYOR_SERIES_AMOUNT_DESC:0 "Dies ist die Anzahl an Divisionen, die ausgebildet werden, bevor der Auftrag aus der Liste entfernt wird.\n\nMit der Einstellung 'endlos' bildet jeder Auftrag eine neue Division aus, sobald die vorherige Division eingesetzt wurde."
 CONVEYOR_SERIES_DECREASE_DESC:0 "Verringert die Anzahl der Divisionen, die pro Auftrag erstellt wird.\n\nMit der Einstellung 'endlos' bildet jeder Auftrag eine neue Division aus, sobald die vorherige Division eingesetzt wurde."
 CONVEYOR_LOW_PRIORITY_DESC:0 "Niedrige Priorität"
 CONVEYOR_MEDIUM_PRIORITY_DESC:0 "Mittlere Priorität"
 CONVEYOR_HIGH_PRIORITY_DESC:0 "Hohe Priorität"
 CONVEYOR_CAN_NOT_TRAIN:0 "§RNicht genügend Ausrüstung zur Ausbildung§!"
 CONVEYOR_CAN_NOT_MANPOWER_TRAIN:0 "§RNicht genügend Mannstärke zur Ausbildung§!"
 CONVEYOR_CAN_NOT_TRAIN_COUNT:1 "§RNicht genügend Mannstärke, um $DIVS|H$ der Divisionen auszubilden§!"
 CONVEYOR_COLLAPSE_DESC:0 "§GKlicken§! zum Ausklappen"
 CONVEYOR_EXPAND_DESC:0 "§GKlicken§! zum Einklappen"
 CONVEYOR_MOVE_UP:0 "§GKlicken§!, um nach oben zu bewegen\n§GUmschalt+Klicken§!, um ganz nach oben zu bewegen"
 CONVEYOR_MOVE_DOWN:0 "§GKlicken§!, um nach unten zu bewegen\n§GUmschalt+Klicken§!, um ganz nach unten zu bewegen"
 DEPLOYMENT_LOW_PRIORITY_DESC:0 "Niedrige Ausrüstungspriorität"
 DEPLOYMENT_MEDIUM_PRIORITY_DESC:0 "Mittlere Ausrüstungspriorität"
 DEPLOYMENT_HIGH_PRIORITY_DESC:0 "Hohe Ausrüstungspriorität"
 UPGRADE_HIGH_PRIORITY:0 "§THohe Verstärkungspriorität§!"
 UPGRADE_MEDIUM_PRIORITY:0 "§TMittlere Verstärkungspriorität§!"
 UPGRADE_LOW_PRIORITY:0 "§TNiedrige Verstärkungspriorität§!"
 CONVEYOR_HAS_BAD_LOCATION:0 "Das Zielgebiet für die Einheit ist §Runzulässig§!."
 CONVEYOR_TRAINING_NOT_FINISHED:0 "Ausbildung ist noch nicht abgeschlossen."
 CONVEYOR_SERIES_CURRENT_AMOUNT_DESC:0 "Aktuelle Seriennummer des Auftrags."
 CONVEYOR_LINE_SERIES_BASE:0 "$CURRENT$/$TARGET$"                                                                            
